export interface Hall {
  a: Seat[];
  b: Seat[];
  c: Seat[];
  d: Seat[];
  e: Seat[];
  f: Seat[];
  g: Seat[];
  h: Seat[];
}

interface Seat {
  id: number;
  hall: number;
  row: string;
  type: string;
  seat: number;
  seat2: number;
  price: number;
}

export const hall1: Hall = {
  a: [
    { id: 1, hall: 1, row: "A", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 2, hall: 1, row: "A", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 3, hall: 1, row: "A", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 4, hall: 1, row: "A", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 5, hall: 1, row: "A", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 6, hall: 1, row: "A", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 7, hall: 1, row: "A", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 8, hall: 1, row: "A", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 9, hall: 1, row: "A", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 10,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 12,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 14,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 15,
      hall: 1,
      row: "A",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  b: [
    { id: 16, hall: 1, row: "B", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 17, hall: 1, row: "B", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 15, hall: 1, row: "B", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 19, hall: 1, row: "B", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 20, hall: 1, row: "B", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 21, hall: 1, row: "B", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 22, hall: 1, row: "B", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 23, hall: 1, row: "B", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 24, hall: 1, row: "B", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 25,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 26,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 27,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 28,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 29,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 30,
      hall: 1,
      row: "B",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  c: [
    { id: 31, hall: 1, row: "C", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 32, hall: 1, row: "C", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 33, hall: 1, row: "C", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 34, hall: 1, row: "C", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 35, hall: 1, row: "C", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 36, hall: 1, row: "C", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 37, hall: 1, row: "C", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 38, hall: 1, row: "C", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 39, hall: 1, row: "C", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 40,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 41,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 42,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 43,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 44,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 45,
      hall: 1,
      row: "C",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  d: [
    { id: 46, hall: 1, row: "D", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 47, hall: 1, row: "D", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 48, hall: 1, row: "D", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 49, hall: 1, row: "D", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 50, hall: 1, row: "D", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 51, hall: 1, row: "D", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 52, hall: 1, row: "D", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 53, hall: 1, row: "D", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 54, hall: 1, row: "D", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 55,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 56,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 57,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 58,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 59,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 60,
      hall: 1,
      row: "D",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  e: [
    { id: 61, hall: 1, row: "E", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 62, hall: 1, row: "E", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 63, hall: 1, row: "E", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 64, hall: 1, row: "E", type: "ds", seat: 4, seat2: 5, price: 15 },
    { id: 65, hall: 1, row: "E", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 66, hall: 1, row: "E", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 67, hall: 1, row: "E", type: "ds", seat: 8, seat2: 9, price: 15 },
    { id: 68, hall: 1, row: "E", type: "ds", seat: 10, seat2: 11, price: 15 },
    { id: 69, hall: 1, row: "E", type: "ss", seat: 12, seat2: 0, price: 11 },
    {
      id: 70,
      hall: 1,
      row: "E",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 71,
      hall: 1,
      row: "E",
      type: "ds",
      seat: 14,
      seat2: 15,
      price: 15,
    },
    {
      id: 72,
      hall: 1,
      row: "E",
      type: "ss",
      seat: 16,
      seat2: 0,
      price: 11,
    },
    {
      id: 74,
      hall: 1,
      row: "E",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
    {
      id: 73,
      hall: 1,
      row: "E",
      type: "ss",
      seat: 18,
      seat2: 0,
      price: 11,
    },
    {
      id: 75,
      hall: 1,
      row: "E",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
  ],
  f: [
    { id: 76, hall: 1, row: "F", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 77, hall: 1, row: "F", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 78, hall: 1, row: "F", type: "ds", seat: 3, seat2: 4, price: 15 },
    { id: 79, hall: 1, row: "F", type: "ds", seat: 5, seat2: 6, price: 15 },
    { id: 80, hall: 1, row: "F", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 81, hall: 1, row: "F", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 82, hall: 1, row: "F", type: "ds", seat: 9, seat2: 10, price: 15 },
    { id: 83, hall: 1, row: "F", type: "ds", seat: 11, seat2: 12, price: 15 },
    { id: 84, hall: 1, row: "F", type: "ss", seat: 13, seat2: 0, price: 11 },
    {
      id: 85,
      hall: 1,
      row: "F",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 86,
      hall: 1,
      row: "F",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 87,
      hall: 1,
      row: "F",
      type: "ds",
      seat: 17,
      seat2: 18,
      price: 15,
    },
    {
      id: 88,
      hall: 1,
      row: "F",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
    {
      id: 89,
      hall: 1,
      row: "F",
      type: "ss",
      seat: 20,
      seat2: 0,
      price: 11,
    },
    {
      id: 90,
      hall: 1,
      row: "F",
      type: "ss",
      seat: 21,
      seat2: 0,
      price: 11,
    },
  ],
  g: [
    { id: 91, hall: 1, row: "G", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 92, hall: 1, row: "G", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 93, hall: 1, row: "G", type: "ds", seat: 3, seat2: 4, price: 15 },
    { id: 94, hall: 1, row: "G", type: "ds", seat: 5, seat2: 6, price: 15 },
    { id: 95, hall: 1, row: "G", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 96, hall: 1, row: "G", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 97, hall: 1, row: "G", type: "ds", seat: 9, seat2: 10, price: 15 },
    { id: 98, hall: 1, row: "G", type: "ds", seat: 11, seat2: 12, price: 15 },
    { id: 99, hall: 1, row: "G", type: "ss", seat: 13, seat2: 0, price: 11 },
    {
      id: 100,
      hall: 1,
      row: "G",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 101,
      hall: 1,
      row: "G",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 102,
      hall: 1,
      row: "G",
      type: "ds",
      seat: 17,
      seat2: 18,
      price: 15,
    },
    {
      id: 103,
      hall: 1,
      row: "G",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
    {
      id: 104,
      hall: 1,
      row: "G",
      type: "ss",
      seat: 20,
      seat2: 0,
      price: 11,
    },
    {
      id: 105,
      hall: 1,
      row: "G",
      type: "ss",
      seat: 21,
      seat2: 0,
      price: 11,
    },
  ],
  h: [
    {
      id: 106,
      hall: 1,
      row: "H",
      type: "ss",
      seat: 1,
      seat2: 0,
      price: 11,
    },
    {
      id: 107,
      hall: 1,
      row: "H",
      type: "ss",
      seat: 2,
      seat2: 0,
      price: 11,
    },
    {
      id: 108,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 3,
      seat2: 4,
      price: 15,
    },
    {
      id: 109,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 5,
      seat2: 6,
      price: 15,
    },
    {
      id: 110,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 8,
      seat2: 9,
      price: 15,
    },
    {
      id: 111,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 10,
      seat2: 11,
      price: 15,
    },
    {
      id: 112,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 12,
      seat2: 13,
      price: 15,
    },
    {
      id: 111,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 14,
      seat2: 15,
      price: 15,
    },
    {
      id: 114,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 16,
      seat2: 17,
      price: 15,
    },
    {
      id: 115,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 18,
      seat2: 19,
      price: 11,
    },
    {
      id: 116,
      hall: 1,
      row: "H",
      type: "ds",
      seat: 20,
      seat2: 21,
      price: 15,
    },
    {
      id: 117,
      hall: 1,
      row: "H",
      type: "ss",
      seat: 22,
      seat2: 0,
      price: 11,
    },
    {
      id: 118,
      hall: 1,
      row: "H",
      type: "ss",
      seat: 23,
      seat2: 0,
      price: 11,
    },
  ],
};

export const hall2: Hall = {
  a: [
    { id: 1, hall: 2, row: "A", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 2, hall: 2, row: "A", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 3, hall: 2, row: "A", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 4, hall: 2, row: "A", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 5, hall: 2, row: "A", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 6, hall: 2, row: "A", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 7, hall: 2, row: "A", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 8, hall: 2, row: "A", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 9, hall: 2, row: "A", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 10,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 12,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 14,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 15,
      hall: 2,
      row: "A",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  b: [
    { id: 16, hall: 2, row: "B", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 17, hall: 2, row: "B", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 15, hall: 2, row: "B", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 19, hall: 2, row: "B", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 20, hall: 2, row: "B", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 21, hall: 2, row: "B", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 22, hall: 2, row: "B", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 23, hall: 2, row: "B", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 24, hall: 2, row: "B", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 25,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 26,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 27,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 28,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 29,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 30,
      hall: 2,
      row: "B",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  c: [
    { id: 31, hall: 2, row: "C", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 32, hall: 2, row: "C", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 33, hall: 2, row: "C", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 34, hall: 2, row: "C", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 35, hall: 2, row: "C", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 36, hall: 2, row: "C", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 37, hall: 2, row: "C", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 38, hall: 2, row: "C", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 39, hall: 2, row: "C", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 40,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 41,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 42,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 43,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 44,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 45,
      hall: 2,
      row: "C",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  d: [
    { id: 46, hall: 2, row: "D", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 47, hall: 2, row: "D", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 48, hall: 2, row: "D", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 49, hall: 2, row: "D", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 50, hall: 2, row: "D", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 51, hall: 2, row: "D", type: "ds", seat: 6, seat2: 7, price: 15 },
    { id: 52, hall: 2, row: "D", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 53, hall: 2, row: "D", type: "ss", seat: 9, seat2: 0, price: 11 },
    { id: 54, hall: 2, row: "D", type: "ds", seat: 10, seat2: 11, price: 15 },
    {
      id: 55,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 56,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 57,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 58,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
    {
      id: 59,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 16,
      seat2: 0,
      price: 11,
    },
    {
      id: 60,
      hall: 2,
      row: "D",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
  ],
  e: [
    { id: 61, hall: 2, row: "E", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 62, hall: 2, row: "E", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 63, hall: 2, row: "E", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 64, hall: 2, row: "E", type: "ds", seat: 4, seat2: 5, price: 15 },
    { id: 65, hall: 2, row: "E", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 66, hall: 2, row: "E", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 67, hall: 2, row: "E", type: "ds", seat: 8, seat2: 9, price: 15 },
    { id: 68, hall: 2, row: "E", type: "ds", seat: 10, seat2: 11, price: 15 },
    { id: 69, hall: 2, row: "E", type: "ss", seat: 12, seat2: 0, price: 11 },
    {
      id: 70,
      hall: 2,
      row: "E",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 71,
      hall: 2,
      row: "E",
      type: "ds",
      seat: 14,
      seat2: 15,
      price: 15,
    },
    {
      id: 72,
      hall: 2,
      row: "E",
      type: "ss",
      seat: 16,
      seat2: 0,
      price: 11,
    },
    {
      id: 74,
      hall: 2,
      row: "E",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
    {
      id: 73,
      hall: 2,
      row: "E",
      type: "ss",
      seat: 18,
      seat2: 0,
      price: 11,
    },
    {
      id: 75,
      hall: 2,
      row: "E",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
  ],
  f: [
    { id: 76, hall: 2, row: "F", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 77, hall: 2, row: "F", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 78, hall: 2, row: "F", type: "ds", seat: 3, seat2: 4, price: 15 },
    { id: 79, hall: 2, row: "F", type: "ds", seat: 5, seat2: 6, price: 15 },
    { id: 80, hall: 2, row: "F", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 81, hall: 2, row: "F", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 82, hall: 2, row: "F", type: "ds", seat: 9, seat2: 10, price: 15 },
    { id: 83, hall: 2, row: "F", type: "ds", seat: 11, seat2: 12, price: 15 },
    { id: 84, hall: 2, row: "F", type: "ss", seat: 13, seat2: 0, price: 11 },
    {
      id: 85,
      hall: 2,
      row: "F",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 86,
      hall: 2,
      row: "F",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 87,
      hall: 2,
      row: "F",
      type: "ds",
      seat: 17,
      seat2: 18,
      price: 15,
    },
    {
      id: 88,
      hall: 2,
      row: "F",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
    {
      id: 89,
      hall: 2,
      row: "F",
      type: "ss",
      seat: 20,
      seat2: 0,
      price: 11,
    },
    {
      id: 90,
      hall: 2,
      row: "F",
      type: "ss",
      seat: 21,
      seat2: 0,
      price: 11,
    },
  ],
  g: [
    { id: 91, hall: 2, row: "G", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 92, hall: 2, row: "G", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 93, hall: 2, row: "G", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 94, hall: 2, row: "G", type: "ds", seat: 4, seat2: 5, price: 15 },
    { id: 95, hall: 2, row: "G", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 96, hall: 2, row: "G", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 97, hall: 2, row: "G", type: "ds", seat: 8, seat2: 9, price: 15 },
    { id: 98, hall: 2, row: "G", type: "ds", seat: 10, seat2: 11, price: 15 },
    { id: 99, hall: 2, row: "G", type: "ss", seat: 12, seat2: 0, price: 11 },
    {
      id: 100,
      hall: 2,
      row: "G",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 101,
      hall: 2,
      row: "G",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 102,
      hall: 2,
      row: "G",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 103,
      hall: 2,
      row: "G",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
    {
      id: 104,
      hall: 2,
      row: "G",
      type: "ss",
      seat: 18,
      seat2: 0,
      price: 11,
    },
    {
      id: 105,
      hall: 2,
      row: "G",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
  ],
  h: [
    {
      id: 106,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 1,
      seat2: 0,
      price: 11,
    },
    {
      id: 107,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 2,
      seat2: 0,
      price: 11,
    },
    {
      id: 108,
      hall: 2,
      row: "H",
      type: "ds",
      seat: 3,
      seat2: 4,
      price: 15,
    },
    {
      id: 109,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 5,
      seat2: 0,
      price: 11,
    },
    {
      id: 110,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 6,
      seat2: 0,
      price: 11,
    },
    {
      id: 111,
      hall: 2,
      row: "H",
      type: "ds",
      seat: 7,
      seat2: 8,
      price: 15,
    },
    {
      id: 112,
      hall: 2,
      row: "H",
      type: "ds",
      seat: 9,
      seat2: 10,
      price: 15,
    },
    {
      id: 113,
      hall: 2,
      row: "H",
      type: "ds",
      seat: 11,
      seat2: 12,
      price: 15,
    },
    {
      id: 114,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 13,
      seat2: 0,
      price: 11,
    },
    {
      id: 115,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 116,
      hall: 2,
      row: "H",
      type: "ds",
      seat: 14,
      seat2: 15,
      price: 15,
    },
    {
      id: 117,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 16,
      seat2: 0,
      price: 11,
    },
    {
      id: 118,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
    {
      id: 119,
      hall: 2,
      row: "H",
      type: "ss",
      seat: 18,
      seat2: 0,
      price: 11,
    },
  ],
};

export const hall3: Hall = {
  a: [
    { id: 1, hall: 3, row: "A", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 2, hall: 3, row: "A", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 3, hall: 3, row: "A", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 4, hall: 3, row: "A", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 5, hall: 3, row: "A", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 6, hall: 3, row: "A", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 7, hall: 3, row: "A", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 8, hall: 3, row: "A", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 9, hall: 3, row: "A", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 10,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 12,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 11,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 14,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 15,
      hall: 3,
      row: "A",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  b: [
    { id: 16, hall: 3, row: "B", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 17, hall: 3, row: "B", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 15, hall: 3, row: "B", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 19, hall: 3, row: "B", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 20, hall: 3, row: "B", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 21, hall: 3, row: "B", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 22, hall: 3, row: "B", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 23, hall: 3, row: "B", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 24, hall: 3, row: "B", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 25,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 26,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 27,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 28,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 29,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 30,
      hall: 3,
      row: "B",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  c: [
    { id: 31, hall: 3, row: "C", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 32, hall: 3, row: "C", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 33, hall: 3, row: "C", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 34, hall: 3, row: "C", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 35, hall: 3, row: "C", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 36, hall: 3, row: "C", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 37, hall: 3, row: "C", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 38, hall: 3, row: "C", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 39, hall: 3, row: "C", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 40,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 41,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 42,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 43,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 44,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 45,
      hall: 3,
      row: "C",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  d: [
    { id: 46, hall: 3, row: "D", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 47, hall: 3, row: "D", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 48, hall: 3, row: "D", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 49, hall: 3, row: "D", type: "ss", seat: 4, seat2: 0, price: 11 },
    { id: 50, hall: 3, row: "D", type: "ss", seat: 5, seat2: 0, price: 11 },
    { id: 51, hall: 3, row: "D", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 52, hall: 3, row: "D", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 53, hall: 3, row: "D", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 54, hall: 3, row: "D", type: "ss", seat: 9, seat2: 0, price: 11 },
    {
      id: 55,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 56,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 57,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 58,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 59,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 60,
      hall: 3,
      row: "D",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
  e: [
    { id: 61, hall: 3, row: "E", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 62, hall: 3, row: "E", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 63, hall: 3, row: "E", type: "ss", seat: 3, seat2: 0, price: 11 },
    { id: 64, hall: 3, row: "E", type: "ds", seat: 4, seat2: 5, price: 15 },
    { id: 65, hall: 3, row: "E", type: "ss", seat: 6, seat2: 0, price: 11 },
    { id: 66, hall: 3, row: "E", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 67, hall: 3, row: "E", type: "ds", seat: 8, seat2: 9, price: 15 },
    { id: 68, hall: 3, row: "E", type: "ds", seat: 10, seat2: 11, price: 15 },
    { id: 69, hall: 3, row: "E", type: "ss", seat: 12, seat2: 0, price: 11 },
    {
      id: 70,
      hall: 3,
      row: "E",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 71,
      hall: 3,
      row: "E",
      type: "ds",
      seat: 14,
      seat2: 15,
      price: 15,
    },
    {
      id: 72,
      hall: 3,
      row: "E",
      type: "ss",
      seat: 16,
      seat2: 0,
      price: 11,
    },
    {
      id: 74,
      hall: 3,
      row: "E",
      type: "ss",
      seat: 17,
      seat2: 0,
      price: 11,
    },
    {
      id: 73,
      hall: 3,
      row: "E",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
    {
      id: 75,
      hall: 3,
      row: "E",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
  ],
  f: [
    { id: 76, hall: 3, row: "F", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 77, hall: 3, row: "F", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 78, hall: 3, row: "F", type: "ds", seat: 3, seat2: 4, price: 15 },
    { id: 79, hall: 3, row: "F", type: "ds", seat: 5, seat2: 6, price: 15 },
    { id: 80, hall: 3, row: "F", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 81, hall: 3, row: "F", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 82, hall: 3, row: "F", type: "ds", seat: 9, seat2: 10, price: 15 },
    { id: 83, hall: 3, row: "F", type: "ds", seat: 11, seat2: 12, price: 15 },
    { id: 84, hall: 3, row: "F", type: "ss", seat: 11, seat2: 0, price: 11 },
    {
      id: 85,
      hall: 3,
      row: "F",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 86,
      hall: 3,
      row: "F",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 87,
      hall: 3,
      row: "F",
      type: "ds",
      seat: 17,
      seat2: 15,
      price: 15,
    },
    {
      id: 88,
      hall: 3,
      row: "F",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
    {
      id: 89,
      hall: 3,
      row: "F",
      type: "ss",
      seat: 20,
      seat2: 0,
      price: 11,
    },
    {
      id: 90,
      hall: 3,
      row: "F",
      type: "ss",
      seat: 21,
      seat2: 0,
      price: 11,
    },
  ],
  g: [
    { id: 91, hall: 3, row: "G", type: "ss", seat: 1, seat2: 0, price: 11 },
    { id: 92, hall: 3, row: "G", type: "ss", seat: 2, seat2: 0, price: 11 },
    { id: 93, hall: 3, row: "G", type: "ds", seat: 3, seat2: 4, price: 15 },
    { id: 94, hall: 3, row: "G", type: "ds", seat: 5, seat2: 6, price: 15 },
    { id: 95, hall: 3, row: "G", type: "ss", seat: 7, seat2: 0, price: 11 },
    { id: 96, hall: 3, row: "G", type: "ss", seat: 8, seat2: 0, price: 11 },
    { id: 97, hall: 3, row: "G", type: "ds", seat: 9, seat2: 10, price: 15 },
    { id: 98, hall: 3, row: "G", type: "ds", seat: 11, seat2: 12, price: 15 },
    { id: 99, hall: 3, row: "G", type: "ss", seat: 11, seat2: 0, price: 11 },
    {
      id: 100,
      hall: 3,
      row: "G",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 101,
      hall: 3,
      row: "G",
      type: "ds",
      seat: 15,
      seat2: 16,
      price: 15,
    },
    {
      id: 102,
      hall: 3,
      row: "G",
      type: "ds",
      seat: 17,
      seat2: 15,
      price: 15,
    },
    {
      id: 103,
      hall: 3,
      row: "G",
      type: "ss",
      seat: 19,
      seat2: 0,
      price: 11,
    },
    {
      id: 104,
      hall: 3,
      row: "G",
      type: "ss",
      seat: 20,
      seat2: 0,
      price: 11,
    },
    {
      id: 105,
      hall: 3,
      row: "G",
      type: "ss",
      seat: 21,
      seat2: 0,
      price: 11,
    },
  ],
  h: [
    {
      id: 106,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 1,
      seat2: 0,
      price: 11,
    },
    {
      id: 107,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 2,
      seat2: 0,
      price: 11,
    },
    {
      id: 108,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 3,
      seat2: 0,
      price: 11,
    },
    {
      id: 109,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 4,
      seat2: 0,
      price: 11,
    },
    {
      id: 110,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 5,
      seat2: 0,
      price: 11,
    },
    {
      id: 111,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 6,
      seat2: 0,
      price: 11,
    },
    {
      id: 112,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 7,
      seat2: 0,
      price: 11,
    },
    {
      id: 113,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 8,
      seat2: 0,
      price: 11,
    },
    {
      id: 114,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 9,
      seat2: 0,
      price: 11,
    },
    {
      id: 115,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 10,
      seat2: 0,
      price: 11,
    },
    {
      id: 116,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 117,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 12,
      seat2: 0,
      price: 11,
    },
    {
      id: 115,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 11,
      seat2: 0,
      price: 11,
    },
    {
      id: 119,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 14,
      seat2: 0,
      price: 11,
    },
    {
      id: 120,
      hall: 3,
      row: "H",
      type: "ss",
      seat: 15,
      seat2: 0,
      price: 11,
    },
  ],
};

export const blockSeat: number[] = [1, 35, 45, 60, 75, 78, 82, 90, 102];
